# Generated by Django 6.0.6 on 2026-06-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('mobile_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userrole')),
            ],
        ),
    ]
